[auto] Sync version 2402091217.0.0+llamacpp-release.b2110
== Relevant log messages from source repo:

commit e5ca3937c685d6e012ac4db40555d6ec100ff03c
Author: Paul Tsochantaris <ptsochantaris@icloud.com>
Date:   Fri Feb 9 10:48:06 2024 +0000

    llama : do not cap thread count when MoE on CPU (#5419)

    * Not capping thread count when MoE inference is running on CPU

    * Whitespace

commit b2f87cb64db47d799b6f3656855c9caf9792ab2a
Author: Michael Podvitskiy <podvitskiymichael@gmail.com>
Date:   Fri Feb 9 10:56:43 2024 +0100

    ggml : fix `error C2078: too many initializers` for MSVC ARM64 (#5404)

commit 44fbe34360dd760f9e68b4271f21533436397f84
Author: 0cc4m <picard12@live.de>
Date:   Fri Feb 9 06:52:33 2024 +0100

    Fix Vulkan crash on APUs with very little device memory (#5424)

    * Fix Vulkan crash on APUs with very little device memory

    * Fix debug output function names