[auto] Sync version 2403111218.0.0+llamacpp-release.b2399
== Relevant log messages from source repo:

commit 3202361c5b1ba15e695b31209567ef42c22c5c32
Author: Michael Podvitskiy <podvitskiymichael@gmail.com>
Date:   Mon Mar 11 10:28:51 2024 +0100

    ggml, ci : Windows ARM runner and build fixes (#5979)

    * windows arm ci

    * fix `error C2078: too many initializers` with ggml_vld1q_u32 macro for MSVC ARM64

    * fix `warning C4146: unary minus operator applied to unsigned type, result still unsigned`

    * fix `error C2065: '__fp16': undeclared identifier`

commit ecab1c75de68de7c41c254e2ae170d3b07bee6d4
Author: Gilad S <giladgd@users.noreply.github.com>
Date:   Mon Mar 11 10:00:08 2024 +0200

    cmake : fix subdir for `LLAMA_METAL_EMBED_LIBRARY` (#5985)

commit ee35600b9061b1ea0c4ea87fce6844297632b2a8
Author: Georgi Gerganov <ggerganov@gmail.com>
Date:   Mon Mar 11 09:56:47 2024 +0200

    llama : fix F16/F32 downcast + improve names (#5980)

commit be858f620508385ad12d0e5e862010e666ca729c
Author: Kawrakow <48489457+ikawrakow@users.noreply.github.com>
Date:   Mon Mar 11 07:51:49 2024 +0100

    Better 1.5 bit quantization  (#5971)

    * Trying blocvks of 16 for IQ1_S - seems slightly better

    * iq1s_blocks16: Adjust scale fudge factor to 1.125

    * iq1s_blocks16: going to blocks of 32

    with 2048 lattice points, so same bpw.
    This is even better than blocks of 16.
    Should I try blocks of 64? But to keep the same
    bpw, when I go to 4096 lattice points, I need to
    remove blocks alltogether and just have superblocks of
    256 weights.

    * iq1s_blocks16: Use 2*<x^2> as sigma2 in weight adjustment

    * iq1s_blocks16: scalar and AVX2 dot products

    * iq1s_blocks16: CUDA dot product

    * iq1s_blocks16: Metal works, Neon does not

    Metal works but TG is dog slow (35 t/s). PP is OKish (493 t/s).
    Not seeing the bug in the Neon implementation for now.

    * iq1s_blocks16: fixed Neon

    * iq1s_blocks16: very slightly faster TG on Metal

    Still pathetic at 37 t/s

    * iq1s_blocks16: speedup Metal by packing codebook into uint32_t's

    * Formatting

    * iq1s_blocks16: uint32_t codebook is also better in CUDA

    TG-128 is now 204 t/s up from 194 t/s.
    PP-512 is 5890 t/s, so significantly better than other quants

    * iq1s_blocks16: slightly faster Neon dot product

    * iq1s_blocks16: faster AVX2 dot product

    * iq1s_blocks16: adjust to ggml-common.h

    ---------

    Co-authored-by: Iwan Kawrakow <iwan.kawrakow@gmail.com>